### ISSUE TITLE
Test failure due to IoT method invokation error

### ISSUE THREAD

**Issue by dluc** [Azure/iothub-manager-java#56] opened 2017-09-28 06:20 UTC
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description

```
[info] Test com.microsoft.azure.iotsolutions.iothubmanager.services.DevicesTest.invokeMethodAsyncTest started
[error] Test com.microsoft.azure.iotsolutions.iothubmanager.services.DevicesTest.invokeMethodAsyncTest failed: java.lang.AssertionError: Unable to invoke method, took 0.111 sec
[error]     at com.microsoft.azure.iotsolutions.iothubmanager.services.DevicesTest.invokeMethodAsyncTest(DevicesTest.java:307)
[error]     ...
```

**Comment by zhang-hua** [comment] 2017-10-10 07:14
The current test case will lookup all devices which have reported property "SupportedMethods". If any device is found,  'Reboot' method will be invoked. Since the created testing devices doesn't really mean the devices will be running and connect to IotHub. I suspect the issue is caused by other issue of sdk bug when accessing device twin with more than 5 levels nested properties.

**Comment by dluc** [comment] 2017-10-10 17:05
The error message doesn't look like related to the twin. Integration tests for method calls should create one device and use that device, ignoring the others in the registry. This would also isolate the test from other scenarios and SDK bugs.

**Comment by zhang-hua** [comment] 2017-10-20 15:17
Fix in commit https://github.com/Azure/iothub-manager-java/commit/5cdd44883987e11feffbbd0f33721298595b5504

**Closed by zhang-hua** 2017-10-20 15:17 UTC
Labels: bug, P1
