### ISSUE TITLE
Unable to create jobs. Exception thrown when trying to retrieve list of jobs

### ISSUE THREAD

**Issue by jillcary** [Azure/iothub-manager-java#72] opened 2017-11-21 01:09 UTC
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Unable to create jobs.

# Steps to reproduce 

1. deploy java basic solution
1. go to site
1. open dev inspector go to network tab
1. go to devices tab in solution
1. select a device
1. click tags or schedule or reconfigure
1. create tag or etc...
1. look at network history in inspector, and notice....

![pasted_image_at_2017_11_20_04_59_pm](https://user-images.githubusercontent.com/3317135/33049619-d6f2583e-ce15-11e7-8268-bf3c7ef33217.png)

Exception details
```
{  
   "ExceptionType":"java.lang.IllegalArgumentException",
   "ExceptionMessage":"null jobId",
   "Message":"An error has occured",
   "StackTrace":[  
      {  
         "methodName":"scheduleUpdateTwin",
         "fileName":"JobClient.java",
         "lineNumber":86,
         "className":"com.microsoft.azure.sdk.iot.service.jobs.JobClient",
         "nativeMethod":false
      },
      {  
         "methodName":"scheduleTwinUpdateAsync",
         "fileName":"Jobs.java",
         "lineNumber":131,
         "className":"com.microsoft.azure.iotsolutions.iothubmanager.services.Jobs",
         "nativeMethod":false
      },
      {  
         "methodName":"scheduleJobAsync",
         "fileName":"JobsController.java",
         "lineNumber":101,
         "className":"com.microsoft.azure.iotsolutions.iothubmanager.webservice.v1.controllers.JobsController",
         "nativeMethod":false
      },
      {  
         "methodName":"$anonfun$applyOrElse$30",
         "fileName":"Routes.scala",
         "lineNumber":448,
         "className":"router.Routes$$anonfun$routes$1",
         "nativeMethod":false
      },
      {  
         "methodName":"resultCall",
         "fileName":"HandlerInvoker.scala",
         "lineNumber":137,
         "className":"play.core.routing.HandlerInvokerFactory$$anon$4",
         "nativeMethod":false
      },
      {  
         "methodName":"invocation",
         "fileName":"HandlerInvoker.scala",
         "lineNumber":108,
         "className":"play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$8$$anon$2$$anon$1",
         "nativeMethod":false
      },
      {  
         "methodName":"call",
         "fileName":"JavaAction.scala",
         "lineNumber":76,
         "className":"play.core.j.JavaAction$$anon$1",
         "nativeMethod":false
      },
      {  
         "methodName":"call",
         "fileName":"DefaultActionCreator.java",
         "lineNumber":31,
         "className":"play.http.DefaultActionCreator$1",
         "nativeMethod":false
      },
      {  
         "methodName":"$anonfun$apply$2",
         "fileName":"JavaAction.scala",
         "lineNumber":111,
         "className":"play.core.j.JavaAction",
         "nativeMethod":false
      },
      {  
         "methodName":"$anonfun$apply$1",
         "fileName":"Future.scala",
         "lineNumber":655,
         "className":"scala.concurrent.Future$",
         "nativeMethod":false
      },
      {  
         "methodName":"$anonfun$map$1",
         "fileName":"Try.scala",
         "lineNumber":251,
         "className":"scala.util.Success",
         "nativeMethod":false
      },
      {  
         "methodName":"map",
         "fileName":"Try.scala",
         "lineNumber":209,
         "className":"scala.util.Success",
         "nativeMethod":false
      },
      {  
         "methodName":"$anonfun$map$1",
         "fileName":"Future.scala",
         "lineNumber":289,
         "className":"scala.concurrent.Future",
         "nativeMethod":false
      },
      {  
         "methodName":"liftedTree1$1",
         "fileName":"Promise.scala",
         "lineNumber":29,
         "className":"scala.concurrent.impl.Promise",
         "nativeMethod":false
      },
      {  
         "methodName":"$anonfun$transform$1",
         "fileName":"Promise.scala",
         "lineNumber":29,
         "className":"scala.concurrent.impl.Promise",
         "nativeMethod":false
      },
      {  
         "methodName":"run",
         "fileName":"Promise.scala",
         "lineNumber":60,
         "className":"scala.concurrent.impl.CallbackRunnable",
         "nativeMethod":false
      },
      {  
         "methodName":"run",
         "fileName":"HttpExecutionContext.scala",
         "lineNumber":56,
         "className":"play.core.j.HttpExecutionContext$$anon$2",
         "nativeMethod":false
      },
      {  
         "methodName":"execute",
         "fileName":"Execution.scala",
         "lineNumber":70,
         "className":"play.api.libs.streams.Execution$trampoline$",
         "nativeMethod":false
      },
      {  
         "methodName":"execute",
         "fileName":"HttpExecutionContext.scala",
         "lineNumber":48,
         "className":"play.core.j.HttpExecutionContext",
         "nativeMethod":false
      },
      {  
         "methodName":"executeWithValue",
         "fileName":"Promise.scala",
         "lineNumber":68,
         "className":"scala.concurrent.impl.CallbackRunnable",
         "nativeMethod":false
      },
      {  
         "methodName":"onComplete",
         "fileName":"Promise.scala",
         "lineNumber":368,
         "className":"scala.concurrent.impl.Promise$KeptPromise$Kept",
         "nativeMethod":false
      },
      {  
         "methodName":"onComplete$",
         "fileName":"Promise.scala",
         "lineNumber":367,
         "className":"scala.concurrent.impl.Promise$KeptPromise$Kept",
         "nativeMethod":false
      },
      {  
         "methodName":"onComplete",
         "fileName":"Promise.scala",
         "lineNumber":375,
         "className":"scala.concurrent.impl.Promise$KeptPromise$Successful",
         "nativeMethod":false
      },
      {  
         "methodName":"transform",
         "fileName":"Promise.scala",
         "lineNumber":29,
         "className":"scala.concurrent.impl.Promise",
         "nativeMethod":false
      },
      {  
         "methodName":"transform$",
         "fileName":"Promise.scala",
         "lineNumber":27,
         "className":"scala.concurrent.impl.Promise",
         "nativeMethod":false
      },
      {  
         "methodName":"transform",
         "fileName":"Promise.scala",
         "lineNumber":375,
         "className":"scala.concurrent.impl.Promise$KeptPromise$Successful",
         "nativeMethod":false
      },
      {  
         "methodName":"map",
         "fileName":"Future.scala",
         "lineNumber":289,
         "className":"scala.concurrent.Future",
         "nativeMethod":false
      },
      {  
         "methodName":"map$",
         "fileName":"Future.scala",
         "lineNumber":289,
         "className":"scala.concurrent.Future",
         "nativeMethod":false
      },
      {  
         "methodName":"map",
         "fileName":"Promise.scala",
         "lineNumber":375,
         "className":"scala.concurrent.impl.Promise$KeptPromise$Successful",
         "nativeMethod":false
      },
      {  
         "methodName":"apply",
         "fileName":"Future.scala",
         "lineNumber":655,
         "className":"scala.concurrent.Future$",
         "nativeMethod":false
      },
      {  
         "methodName":"apply",
         "fileName":"JavaAction.scala",
         "lineNumber":111,
         "className":"play.core.j.JavaAction",
         "nativeMethod":false
      },
      {  
         "methodName":"$anonfun$apply$2",
         "fileName":"Action.scala",
         "lineNumber":96,
         "className":"play.api.mvc.Action",
         "nativeMethod":false
      },
      {  
         "methodName":"$anonfun$flatMap$1",
         "fileName":"Future.scala",
         "lineNumber":304,
         "className":"scala.concurrent.Future",
         "nativeMethod":false
      },
      {  
         "methodName":"$anonfun$transformWith$1",
         "fileName":"Promise.scala",
         "lineNumber":37,
         "className":"scala.concurrent.impl.Promise",
         "nativeMethod":false
      },
      {  
         "methodName":"run",
         "fileName":"Promise.scala",
         "lineNumber":60,
         "className":"scala.concurrent.impl.CallbackRunnable",
         "nativeMethod":false
      },
      {  
         "methodName":"processBatch",
         "fileName":"BatchingExecutor.scala",
         "lineNumber":55,
         "className":"akka.dispatch.BatchingExecutor$AbstractBatch",
         "nativeMethod":false
      },
      {  
         "methodName":"$anonfun$run$1",
         "fileName":"BatchingExecutor.scala",
         "lineNumber":91,
         "className":"akka.dispatch.BatchingExecutor$BlockableBatch",
         "nativeMethod":false
      },
      {  
         "methodName":"apply",
         "fileName":"JFunction0$mcV$sp.java",
         "lineNumber":12,
         "className":"scala.runtime.java8.JFunction0$mcV$sp",
         "nativeMethod":false
      },
      {  
         "methodName":"withBlockContext",
         "fileName":"BlockContext.scala",
         "lineNumber":81,
         "className":"scala.concurrent.BlockContext$",
         "nativeMethod":false
      },
      {  
         "methodName":"run",
         "fileName":"BatchingExecutor.scala",
         "lineNumber":91,
         "className":"akka.dispatch.BatchingExecutor$BlockableBatch",
         "nativeMethod":false
      },
      {  
         "methodName":"run",
         "fileName":"AbstractDispatcher.scala",
         "lineNumber":40,
         "className":"akka.dispatch.TaskInvocation",
         "nativeMethod":false
      },
      {  
         "methodName":"exec",
         "fileName":"ForkJoinExecutorConfigurator.scala",
         "lineNumber":43,
         "className":"akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask",
         "nativeMethod":false
      },
      {  
         "methodName":"doExec",
         "fileName":"ForkJoinTask.java",
         "lineNumber":260,
         "className":"akka.dispatch.forkjoin.ForkJoinTask",
         "nativeMethod":false
      },
      {  
         "methodName":"runTask",
         "fileName":"ForkJoinPool.java",
         "lineNumber":1339,
         "className":"akka.dispatch.forkjoin.ForkJoinPool$WorkQueue",
         "nativeMethod":false
      },
      {  
         "methodName":"runWorker",
         "fileName":"ForkJoinPool.java",
         "lineNumber":1979,
         "className":"akka.dispatch.forkjoin.ForkJoinPool",
         "nativeMethod":false
      },
      {  
         "methodName":"run",
         "fileName":"ForkJoinWorkerThread.java",
         "lineNumber":107,
         "className":"akka.dispatch.forkjoin.ForkJoinWorkerThread",
         "nativeMethod":false
      }
   ]
}
```

**Comment by zhang-hua** [comment] 2017-11-21 03:28
Root cause: The Web UI is sending job request with uppercase named properties ('JobId', ‘MaxExecutionTimeInSeconds‘, 'QueryCondition') and lowercase properties (jobId, maxExecutionTimeInSeconds, queryCondition) will be returned.

**Comment by zhang-hua** [comment] 2017-11-21 04:13
@jillcary , I just dumped the JSON body between UI and DotNet IoTHub manager service:
request:
```
{
"JobId":"testjob1-b5e661b4-9b66-4404-8681-adbe2cbcaf02",
"QueryCondition":"deviceId in ['Simulated.chiller-02.0','Simulated.chiller-01.0']",
"MaxExecutionTimeInSeconds":0,
"updateTwin":{"tags":{"IsSimulated":"Y","purpose":"test"}}
}
```
response:
···
{
"jobId":"testjob1-b5e661b4-9b66-4404-8681-adbe2cbcaf02",
"maxExecutionTimeInSeconds":0,
"type":4,
"status":7}
···

But Java requires the request and response to be consistent for the case sensitivity. We are using lowercase for jobId, queryCondition etc. I think we should change the JS code of UI to send lowercase properties.

**Comment by zhang-hua** [comment] 2017-11-21 06:06
move this issue to webui project as [833](https://github.com/Azure/pcs-remote-monitoring-webui/issues/833)

**Comment by zhang-hua** [comment] 2017-12-01 03:44
close it since we have created new issues to address it.

**Closed by zhang-hua** 2017-12-01 03:44 UTC
Labels: bug, GA, P1, Triaged
